services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

  mssqlsa:
    container_name: docker-demo-sqlserver-container
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1*
    ports:
      - "1433:1433"

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - index_data:/chroma/.chroma/index
      - /home/frank/workspace/chroma/server.htpasswd:/chroma/server.htpasswd
    ports:
      - 8000:8000
    networks:
      - net




volumes:
  index_data:
    driver: local
  cache:
    driver: local